[package]
name = "start-sshfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tray-item = "*"
# ctrlc = "3.4"

[build-dependencies]
windres = "*"